use proptest::{
    arbitrary::any,
    collection::{SizeRange, vec as arb_vec},
    prop_compose, prop_oneof,
    strategy::{Just, Strategy},
};

use super::record::Record;

/// Input action for the model/system under test.
///
/// These actions map directly to methods that can be called from the reader or writer.
///
/// One notable difference compared to the real types is that acknowledgements here are only
/// allowed to acknowledge one read at a time.
#[derive(Clone, Debug)]
pub enum Action {
    WriteRecord(Record),
    FlushWrites,
    ReadRecord,
    AcknowledgeRead,
    Writeback(Writeback),
    Crash,
}

/// A stream the operating system flushed to disk on its own, ahead of any explicit flush.
/// This allows us to model OS non-determinism in durability.
#[derive(Clone, Debug)]
pub enum Writeback {
    /// The ledger's memory-mapped pages reach disk, the same durable effect as an `msync`.
    LedgerContents,
    /// A data file's dirty tail reaches disk, with the given degree of completeness.
    DataContents { file: u16, tail: TailPersistence },
    /// A single file's directory entry, its creation or deletion, reaches disk.
    DirEntry(DirTarget),
}

/// The file whose directory entry reaches disk.
#[derive(Clone, Debug)]
pub enum DirTarget {
    Ledger,
    DataFile(u16),
}

/// How completely a data file's dirty tail reached disk, modelling append atomicity.
#[derive(Clone, Copy, Debug)]
pub enum TailPersistence {
    /// Every dirty unit landed intact.
    AllDirty,
    /// A trailing unit did not land; the file is truncated at a unit boundary.
    TornAtBoundary,
    /// The trailing unit's size landed but its contents are garbage.
    GarbageBoundary,
}

prop_compose! {
    fn arb_ack_amount(limit: usize)(amount in 1..limit) -> usize {
        amount
    }
}

fn arb_action() -> impl Strategy<Value = Action> {
    // Overall, we want reads and writes to be equal, with slightly fewer acks, and slightly fewer
    // still flushes of writes.
    prop_oneof![
        3 => Just(Action::FlushWrites),
        5 => Just(Action::ReadRecord),
        4 => Just(Action::AcknowledgeRead),
        3 => arb_writeback().prop_map(Action::Writeback),
        1 => Just(Action::Crash),
        5 => any::<(u32, u16, u8, u8)>().prop_map(|(id, base_size, size_offset, event_count)| {
            let size = u32::from(base_size) + u32::from(size_offset);
            let event_count = event_count % 7;
            Action::WriteRecord(Record::new(id, size, u32::from(event_count)))
        }),
    ]
}

fn arb_tail_persistence() -> impl Strategy<Value = TailPersistence> {
    prop_oneof![
        Just(TailPersistence::AllDirty),
        Just(TailPersistence::TornAtBoundary),
        Just(TailPersistence::GarbageBoundary),
    ]
}

fn arb_dir_target() -> impl Strategy<Value = DirTarget> {
    prop_oneof![
        Just(DirTarget::Ledger),
        (0u16..5).prop_map(DirTarget::DataFile)
    ]
}

fn arb_writeback() -> impl Strategy<Value = Writeback> {
    prop_oneof![
        Just(Writeback::LedgerContents),
        (0u16..5, arb_tail_persistence())
            .prop_map(|(file, tail)| Writeback::DataContents { file, tail }),
        arb_dir_target().prop_map(Writeback::DirEntry),
    ]
}

pub fn arb_actions<R>(len_range: R) -> impl Strategy<Value = Vec<Action>>
where
    R: Into<SizeRange>,
{
    arb_vec(arb_action(), len_range).prop_map(sanitize_raw_actions)
}

/// Sanitizes raw actions generated by proptest into a valid sequence.
///
/// While we obviously want proptest to generate randomized orderings of actions to exercise our
/// model and our system under test (SUT), there are certain combinations/orderings that are simply
/// not valid.  For example, an acknowledgement is only generated by the user of a buffer once
/// they've gotten a record from a `read` operation, so allowing an acknowledgement to exist in an
/// action sequence where there is no read is not valid and never will be.  There is no reason to
/// test such a sequence.
pub fn sanitize_raw_actions(actions: Vec<Action>) -> Vec<Action> {
    let mut unread_event_count: usize = 0;
    let mut unacked_events: usize = 0;

    actions
        .into_iter()
        .filter_map(|a| match a {
            Action::WriteRecord(record) => {
                unread_event_count += 1;
                Some(Action::WriteRecord(record))
            }
            Action::ReadRecord => {
                if unread_event_count > 0 {
                    unread_event_count -= 1;
                    unacked_events += 1;
                }
                Some(Action::ReadRecord)
            }
            Action::AcknowledgeRead => (unacked_events > 0).then(|| {
                unacked_events -= 1;
                Action::AcknowledgeRead
            }),
            Action::FlushWrites => Some(Action::FlushWrites),
            // The OS flushing a stream is always a valid thing to happen.
            Action::Writeback(w) => Some(Action::Writeback(w)),
            // A crash can happen at any point and invalidates outstanding read/ack accounting,
            // since the reader restarts from its last durable position after reopen.
            Action::Crash => {
                unread_event_count += unacked_events;
                unacked_events = 0;
                Some(Action::Crash)
            }
        })
        .collect::<Vec<_>>()
}
